services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-payroll}
      POSTGRES_PASSWORD: ${DB_PASS:-secret123}
      POSTGRES_DB: ${DB_NAME:-payroll_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      # รัน .sql ในครั้งแรกที่ data dir ว่าง
      - ../db/migrations:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
