version: "3.9"
services:
  db:
    image: postgres:16
    container_name: payroll-db
    environment:
      POSTGRES_USER: payroll_user
      POSTGRES_PASSWORD: payroll_pass
      POSTGRES_DB: payroll
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../backend/db/migrations:/docker-entrypoint-initdb.d:ro  # รัน 001_init.sql, 002_seed_data.sql อัตโนมัติ

  pgadmin:
    image: dpage/pgadmin4
    container_name: payroll-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payroll.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata:
